module.exports = {
  businessModel: require('./businessModel'),
  companyAnnualRevenue: require('./companyAnnualRevenue'),
  companyHeadCount: require('./companyHeadCount'),
  deliveryModel: require('./deliveryModel'),
  industry: require('./industry'),
  jobTitle: require('./jobTitle'),
  functionalRole: require('./functionalRole'),
  businessProcessArea: require('./businessProcessArea'),
  developmentSoftwareType: require('./developmentSoftwareType'),
  enterpriseSoftwareWithinBPA: require('./enterpriseSoftwareWithinBPA'),
  enterpriseSoftware: require('./enterpriseSoftware'),
  intendedScaleModel: require('./intendedScaleModel'),
  professionalLevel: require('./professionalLevel'),
  softwareRating: require('./softwareRating'),
  vendorService: require('./vendorService'),
  vendorType: require('./vendorType'),
  tag: require('./tag'),
  developmentSoftware: require('./developmentSoftware'),
  developmentLanguage: require('./developmentLanguage'),
  softwareClass: require('./softwareClass'),
  targetMarketSize: require('./targetMarketSize'),
  pricingModel: require('./pricingModel'),
  deviceSupported: require('./deviceSupported'),
  relationTypes: require('./connectionRelation'),
};
